titel: Siri Paramesh
logo: ../Profile.jpeg
description: Student majoring in Electronics and Communications with a minors in Computer Science and an interest in Aerospace.
<br>
I am into Cross-disciplinary studies. Wants to learn it all and know it all 
theme: jekyll-theme-minimal
