titel: Siri Paramesh
logo: ../Profile.jpeg
description: Student majoring in Electronics and Communications with a minors in Computer Science and an interest in Aerospace. 
theme: jekyll-theme-minimal
